CREATE TABLE [dbo].[Staging Area] (
    [Index]                                               INT            NULL,
    [ code_site]                                          FLOAT (53)     NULL,
    [Nom_site]                                            NVARCHAR (255) NULL,
    [Gouvernorat]                                         NVARCHAR (255) NULL,
    [Délégation]                                          NVARCHAR (255) NULL,
    [secteur (عمادة)]                                     NVARCHAR (255) NULL,
    [Longitude]                                           FLOAT (53)     NULL,
    [Latitude]                                            FLOAT (53)     NULL,
    [Nombre de cellules]                                  FLOAT (53)     NULL,
    [Hauteur Mat/pylône au-dessus du sol (m)]             FLOAT (53)     NULL,
    [Type et capacité de lien de transmission (Backhaul)] NVARCHAR (255) NULL,
    [Date de mise en service]                             NVARCHAR (255) NULL,
    [Technologie]                                         NVARCHAR (255) NULL,
    [BSC(2G)]                                             NVARCHAR (255) NULL,
    [Nombre de trx(2G)]                                   FLOAT (53)     NULL,
    [Bande de fréquences(2G)]                             NVARCHAR (255) NULL,
    [fréquences d'émission(2G)]                           FLOAT (53)     NULL,
    [fréquences de réception(2G)]                         FLOAT (53)     NULL,
    [azimut(2G)]                                          FLOAT (53)     NULL,
    [Tits mécanques et électriques de chaque antenne(2G)] FLOAT (53)     NULL,
    [PIRE(2G)]                                            FLOAT (53)     NULL,
    [Nombre d'antennes (2G)]                              FLOAT (53)     NULL,
    [Type d’installation (sur toit / sur pylône…)(2G)]    NVARCHAR (255) NULL,
    [Nombre et numéros de canaux RF(2G)]                  FLOAT (53)     NULL,
    [Taux de blocage(2G)]                                 FLOAT (53)     NULL,
    [Taux de coupure(2G)]                                 FLOAT (53)     NULL,
    [Trafic voix mensuel moyen (min)(2G)]                 FLOAT (53)     NULL,
    [Trafic Data mensuel moyen (Go)(2G)]                  FLOAT (53)     NULL,
    [Taux de disponibilité sur 24H(2G)]                   FLOAT (53)     NULL,
    [Bandes de fréquences(3G)]                            NVARCHAR (255) NULL,
    [Largeur de bande(3G)]                                NVARCHAR (255) NULL,
    [Azimut(3G)]                                          NVARCHAR (255) NULL,
    [Tits mécanques et électriques de chaque antenne(3G)] NVARCHAR (255) NULL,
    [PIRE(3G)]                                            NVARCHAR (255) NULL,
    [Nombre d'antennes MIMO(3G)]                          NVARCHAR (255) NULL,
    [Type d’installation (sur toit / sur pylône…)(3G)]    NVARCHAR (255) NULL,
    [Nombre et numéros de canaux RF(3G)]                  NVARCHAR (255) NULL,
    [Taux de blocage(3G)]                                 NVARCHAR (255) NULL,
    [Taux de coupure(3G)]                                 NVARCHAR (255) NULL,
    [Trafic voix mensuel moyen (min)(3G)]                 NVARCHAR (255) NULL,
    [Trafic Data mensuel moyen (Go)(3G)]                  NVARCHAR (255) NULL,
    [Taux de disponibilité sur 24H(3G)]                   NVARCHAR (255) NULL,
    [Nombre de porteuses(4G)]                             NVARCHAR (255) NULL,
    [Bandes de fréquences(4G)]                            NVARCHAR (255) NULL,
    [Largeur de bande(4G)]                                NVARCHAR (255) NULL,
    [Azimut(4G)]                                          NVARCHAR (255) NULL,
    [Tits mécanques et électriques de chaque antenne(4G)] NVARCHAR (255) NULL,
    [PIRE(4G)]                                            NVARCHAR (255) NULL,
    [Nombre d'antennes MIMO(4G)]                          NVARCHAR (255) NULL,
    [Type d’installation (sur toit / sur pylône…)(4G)]    NVARCHAR (255) NULL,
    [Nombre et numéros de canaux RF(4G)]                  NVARCHAR (255) NULL,
    [Taux de blocage(4G)]                                 NVARCHAR (255) NULL,
    [Taux de coupure(4G)]                                 NVARCHAR (255) NULL,
    [Trafic VoLTE mensuel moyen (Go)(4G)]                 NVARCHAR (255) NULL,
    [Trafic Data mensuel moyen (Go)(4G)]                  NVARCHAR (255) NULL,
    [Taux de disponibilité sur 24H(4G)]                   NVARCHAR (255) NULL
);

